# Generated by Django 4.2.6 on 2023-10-07 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='selo_fonografico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sebo_discos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('ano', models.IntegerField()),
                ('pais', models.CharField(max_length=20)),
                ('genero', models.CharField(choices=[('t', 'terror'), ('d', 'drama')], max_length=10)),
                ('quantidade', models.IntegerField()),
                ('artistas', models.ManyToManyField(to='core.artista')),
                ('selo_fonografico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.selo_fonografico')),
            ],
        ),
    ]
