# Generated by Django 4.2.6 on 2023-10-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sebo_discos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('selo_fonografico', models.CharField(max_length=200)),
                ('ano', models.IntegerField()),
                ('pais', models.CharField(max_length=20)),
                ('genero', models.CharField(choices=[('feminino', 'f'), ('masculino', 'm')], max_length=10)),
                ('quantidade', models.IntegerField()),
            ],
        ),
    ]
